### ISSUE TITLE
Sweep: Replace Fastify Server with Python Django

### ISSUE THREAD

**Issue by justinthelaw** [justinthelaw/smarter-bullets#101]
Replace all of the TypeScript and Fastify contents within the directory "server", with the equivalent Python and Django code and dependencies required to operate the server. This includes all of the utils, constants, and health routes within the "server" directory.

**Comment by justinthelaw** [comment]
Please add tests for all Python components, and remove all files within the server directory that are related to TypeScript, NPM, JavaScript and Fastify. Also ensure that health check is implemented correctly in the Django route.

**Comment by kevinlu1248** [comment]
@justinthelaw 

Hey Justin, I'm one of the co-founders of Sweep and it looks like you've been solving a lot of tech debt and small features in Smarter Bullets with Sweep. Would love to have a chat about how you're using Sweep, what's been working and what hasn't. My calendly's at https://calendly.com/d/2n5-3qf-9xy/user-interview or we can hop on a Discord call in our community at https://discord.gg/sweep-ai

Kevin
Co-founder of Sweep AI
