### ISSUE TITLE
Docs(Contributing): Pure Linux and ARM Development Environment

### ISSUE THREAD

**Issue by justinthelaw** [justinthelaw/smarter-bullets#47]
Currently, the local development environment setup by this repository has only been tested on Mac (Intel), Windows, and WSL environments. Mac (ARM) and pure Linux machines have not been tested with the scripts and instructions within the `README.md`.

The expected end-state is a set of scripts and instructions that work for all developers across all possible local development environments.

**Comment by ananaso** [comment]
Have tested on Linux environment, seems to all be working without issue.
```bash
$ cat /etc/*-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

**Comment by ananaso** [comment]
Everything also appears to be a go on an M1 MacBook Pro
```bash
% system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 13.4.1 (22F82)
      Kernel Version: Darwin 22.5.0
```
![image](https://github.com/justinthelaw/smarter-bullets/assets/44685609/1a3170bd-8d01-47fd-be3c-0a6294fd34b4)
