### ISSUE TITLE
Sweep: Create Completed T5 Training Dataset

### ISSUE THREAD

**Issue by justinthelaw** [justinthelaw/smarter-bullets#76]
TARGET FILE: forge/data/training/bullet_summaries_evaluations.jsonl

DIRECTORY FOR CONTEXT: forge/

TASK: Using the existing entries within the TARGET FILE and the context in DIRECTORY FOR CONTEXT, take all of the Summary-Evaluation pairs within forge/data/training/bullet_evaluations.jsonl and modify all of the "<ADD THE FULL-FORM PARAGRAPH>" matching the pattern of generation already seen in forge/data/training/bullet_summaries_evaluations.jsonl. Add all of those Summary-Evaluation pairs into the forge/data/training/bullet_summaries_evaluations.jsonl file as new JSON lines. There should be approximately 33,000+ entries in the file once you are done appending all of the Summar-Evaluation pairs. Do this in delayed chunks so that you do overload your context and/or your rate limiter.

**Comment by justinthelaw** [comment]
Please try again.

**Comment by wwzeng1** [comment]
Hey Justin, just got an alert for this. Sorry, but we don't support data processing at the moment!

**Comment by justinthelaw** [comment]
Instead of using forge/data/training/bullet_summaries_evaluations.jsonl. Just try to at least triple the number of entries within forge/data/training/bullet_evaluations.jsonl by following the pattern of the entries already in the JSONL.
